name: Postman API Tests

on:
  push:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Start server
      run: |
        nohup npm start > output.log &
        sleep 10

    - name: Run Newman tests
      run: npx newman run Library.postman_collection.json -e Library_dev.postman_environment.json --reporters=cli,htmlextra
